# Generated by Django 4.0.3 on 2022-04-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('color_car', models.CharField(max_length=100)),
                ('details_car', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('image_car', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slug', models.SlugField(default='slug', editable=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
            ],
        ),
    ]
